name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
        working-directory: action-a
    steps:
      - name: Checkout
      - uses: actions/checkout@v1
        with:
          MY_NAME: "Mona"
        run: |
          .\entrypoint.ps1
